# 基础配置
baseURL = "localhost"
languageCode = 'zh-CN'
title = '短松江月'
theme = 'hugo-focus'
ignoreLogs = ['warning-goldmark-raw-html']

# 设置默认语言
defaultContentLanguage = "zh"
# 将内容放在语言子目录下
# defaultContentLanguageInSubdir = false
defaultContentLanguageInSubdir = true  # 重要：默认语言也在子目录中

# 基础优化配置
enableGitInfo = true
hasCJKLanguage = true
summaryLength = 140

# 全局功能开关
comments = true
math = true





# 隐私相关配置
[privacy]
[privacy.x]
disable = false
enableDNT = false
simple = false

[privacy.vimeo]
disabled = false
simple = true

# 评论服务配置
[services.disqus]
shortname = 'caoyang2002.vercel.app'

# 分类配置
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# Giscus评论系统配置
[params.giscus]
repo = 'caoyang2002/caoyang2002'
repoId = 'R_kgDONgnnzg'
category = 'Announcements'
categoryId = 'DIC_kwDONgnnzs4ClayH'
mapping = 'pathname'
strict = "0"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "top"
# theme = "preferred_color_scheme"
crossorigin = "anonymous"
theme = 'light'
lang = 'zh-CN'

# RSS 订阅配置
[params.rss]
limit = 20
fullContent = true

# 文章配置
[permalinks]
posts = "/post/:year/:month/:filename/"

# 图片配置
[imaging]
quality = 75
resampleFilter = "Lanczos"
anchor = "Smart"

[imaging.exif]
disableDate = true
disableLatLong = true



# 主题参数配置
[params]
color = 'linen'
subtitle = 'The Best Widgets on Earth'
toc = true

# 个人信息配置
avatar = '/about/avatar.jpg'
bio = '难事必作于易，天下大事必作于细。'
author = "Simons"
logo = "/site/logo/logo.jpg"
# 全局启用目录
# 分页
paginationSize = 10
paginatePath = "page"



# 社交媒体链接
twitter = 'caoyang2002'
github = 'caoyang2002'
instagram = 'caoyang2002'



disablePostNavigation = false # 禁用文章导航

# 其他设置
disableHLJS = false # 禁用 highlight.js 代码高亮
# disablePostNavigation = true             # 禁用文章导航
monoDarkIcon = false # 使用单色暗模式图标
math = true        # 全局启用 KaTeX 数学公式排版
localKatex = false # 使用本地 KaTeX js/css 而不是 CDN
# graphCommentId = "YOUR_GRAPH_COMMENT_ID" # 使用 Graph Comment（Disqus 替代品）
favicon = "favicon.ico"                 # 自定义网站图标
appleTouchIcon = "apple-touch-icon.png" # 自定义苹果设备触摸图标

# RTL 支持
direction = "ltr" # 支持从右到左的语言排版

pageViewConter = true

[params.contact]
email = 'info@example.org'
phone = '+1 202-555-1212'

# 主题模块导入
# [[module.imports]]
# path = "github.com/caoyang2002/hugo-focus"

[outputs]
home = ["HTML", "RSS", "JSON"]

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"




# 多语言支持

# 语言配置
[languages]
# 中文
[languages.zh]
contentDir = 'content/zh'
staticDir = ['static']
notFound = "/404.html"
disabled = false
languageCode = 'zh-CN'
languageDirection = 'ltr'
languageName = 'Chinese'
title = '短松江月'
weight = 1
[languages.zh.params]
subtitle = '中文文档'

# 英语
[languages.en]
contentDir = 'content/en'
staticDir = ['static']

disabled = false
languageCode = 'en-US'
languageDirection = 'ltr'
languageName = 'English'
title = '短松江月'
weight = 2
[languages.en.params]
subtitle = 'Reference, Tutorials, and Explanations'

# 西班牙语
[languages.es]
contentDir = 'content/es'
staticDir = ['static']
disabled = false
languageCode = 'es-ES'
languageDirection = 'ltr'
languageName = 'Español'
title = '短松江月'
weight = 3
[languages.es.params]
subtitle = 'Referencia, Tutoriales y Explicaciones'


#
#

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # 允许 HTML 内容

    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"

      [markup.goldmark.parser.attribute]
        block = true
        title = true

    [markup.goldmark.extensions]
      strikethrough = true
      table = true
      taskList = true
      typographer = true

      [markup.goldmark.extensions.passthrough]
        enable = true

        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

          # Markdown配置
          [markup.tableOfContents]
          endLevel = 4
          startLevel = 1
          ordered = false
          # startLevel = 2
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
